version: '3'

services:
  protoc-go:
    build:
      context: .
      dockerfile: ./docker/protoc/go/Dockerfile
    working_dir: /usr/src/
    volumes:
      - .:/usr/src/
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro

  protoc-elm:
    build:
      context: .
      dockerfile: ./docker/protoc/elm/Dockerfile
    working_dir: /usr/src/
    volumes:
      - .:/usr/src/
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro

  protoc-docs:
    build:
      context: .
      dockerfile: ./docker/protoc/docs/Dockerfile
    working_dir: /usr/src/
    volumes:
      - ./:/usr/src/
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwd
    networks:
      - default
    profiles:
      - dev
      - backend

  mongo-admin:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: passwd
      ME_CONFIG_MONGODB_URL: mongodb://root:passwd@mongo:27017
    profiles:
      - dev
      - backend
    depends_on:
      - mongo

  backend:
    build:
      context: .
      dockerfile: ./docker/app/backend/dev/Dockerfile
    working_dir: /usr/src/
    ports:
      - 3000:3000
    volumes:
      - ./backend/:/usr/src/backend
    networks:
      - default
    profiles:
      - dev
      - backend
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: ./docker/app/frontend/dev/Dockerfile
    working_dir: /usr/src/
    ports:
      - 3000:8888
    volumes:
      - ./frontend/:/usr/src/frontend
    networks:
      - default
    profiles:
      - dev
      - frontend

  auth-emulator:
    build:
      context: .
      dockerfile: ./docker/firebase/Dockerfile
    working_dir: /usr/firebase
    ports:
      # Emulator Posts
      - 9099:9099 # Authentication
      - 4000:4000 # UI
      - 5001:5001 # Functions
      - 9299:9299 # Eventarc
      - 9000:9000 # Realtime Database
      - 8080:8080 # Firestore
      - 9199:9199 # Storage
      - 5000:5000 # Hosting
      - 8085:8085 # Pub/Sub
    environment:
      GCLOUD_PROJECT: todo-app-ad242
    volumes:
      - ./firebase:/usr/firebase
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    command: firebase emulators:start --only auth --import ./data --export-on-exit
    networks:
      - default
    profiles:
      - dev
      - backend
      - frontend
