{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Api.Task exposing (Info, decodeInfo, defaultInfo, encodeInfo, fieldNumbersInfo)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 3.2.0
- `protoc` 4.24.4
- the following specification files: `task.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.


@docs Info, decodeInfo, defaultInfo, encodeInfo, fieldNumbersInfo
-}

import Proto.Api.Internals_
import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `Info`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersInfo : { title : Int, description : Int, limit : Int, priority : Int, status : Int, labels : Int }
fieldNumbersInfo =
    Proto.Api.Internals_.fieldNumbersProto__Api__Task__Info


{-| Default for Info. Should only be used for 'required' decoders as an initial value.


-}
defaultInfo : Info
defaultInfo =
    Proto.Api.Internals_.defaultProto__Api__Task__Info


{-| Declares how to decode a `Info` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeInfo : Protobuf.Decode.Decoder Info
decodeInfo =
    Proto.Api.Internals_.decodeProto__Api__Task__Info


{-| Declares how to encode a `Info` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeInfo : Info -> Protobuf.Encode.Encoder
encodeInfo =
    Proto.Api.Internals_.encodeProto__Api__Task__Info


{-| `Info` message


-}
type alias Info =
    Proto.Api.Internals_.Proto__Api__Task__Info
