{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Api.TaskService exposing (create, delete, get, list, update)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 3.2.0
- `protoc` 4.24.4
- the following specification files: `task.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.


@docs create, delete, get, list, update
-}

import Grpc.Internal
import Proto.Api


{-| A template for a gRPC call to the method 'Delete' sending a `TaskDeleteRequest` to get back a `TaskDeleteResponse`.


-}
delete : Grpc.Internal.Rpc Proto.Api.TaskDeleteRequest Proto.Api.TaskDeleteResponse
delete =
    Grpc.Internal.Rpc
        { service = "TaskService"
        , package = "api"
        , rpcName = "Delete"
        , encoder = Proto.Api.encodeTaskDeleteRequest
        , decoder = Proto.Api.decodeTaskDeleteResponse
        }


{-| A template for a gRPC call to the method 'Update' sending a `TaskUpdateRequest` to get back a `TaskUpdateResponse`.


-}
update : Grpc.Internal.Rpc Proto.Api.TaskUpdateRequest Proto.Api.TaskUpdateResponse
update =
    Grpc.Internal.Rpc
        { service = "TaskService"
        , package = "api"
        , rpcName = "Update"
        , encoder = Proto.Api.encodeTaskUpdateRequest
        , decoder = Proto.Api.decodeTaskUpdateResponse
        }


{-| A template for a gRPC call to the method 'Create' sending a `TaskCreateRequest` to get back a `TaskCreateResponse`.


-}
create : Grpc.Internal.Rpc Proto.Api.TaskCreateRequest Proto.Api.TaskCreateResponse
create =
    Grpc.Internal.Rpc
        { service = "TaskService"
        , package = "api"
        , rpcName = "Create"
        , encoder = Proto.Api.encodeTaskCreateRequest
        , decoder = Proto.Api.decodeTaskCreateResponse
        }


{-| A template for a gRPC call to the method 'Get' sending a `TaskGetRequest` to get back a `TaskGetResponse`.


-}
get : Grpc.Internal.Rpc Proto.Api.TaskGetRequest Proto.Api.TaskGetResponse
get =
    Grpc.Internal.Rpc
        { service = "TaskService"
        , package = "api"
        , rpcName = "Get"
        , encoder = Proto.Api.encodeTaskGetRequest
        , decoder = Proto.Api.decodeTaskGetResponse
        }


{-| A template for a gRPC call to the method 'List' sending a `TaskListRequest` to get back a `TaskListResponse`.


-}
list : Grpc.Internal.Rpc Proto.Api.TaskListRequest Proto.Api.TaskListResponse
list =
    Grpc.Internal.Rpc
        { service = "TaskService"
        , package = "api"
        , rpcName = "List"
        , encoder = Proto.Api.encodeTaskListRequest
        , decoder = Proto.Api.decodeTaskListResponse
        }
