{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Api.Todo exposing (ToDo, ToDoAddRequest, ToDoDeleteRequest, ToDoGetRequest, ToDoListRequest, ToDoListResponse, decodeToDo, decodeToDoAddRequest, decodeToDoDeleteRequest, decodeToDoGetRequest, decodeToDoListRequest, decodeToDoListResponse, defaultToDo, defaultToDoAddRequest, defaultToDoDeleteRequest, defaultToDoGetRequest, defaultToDoListRequest, defaultToDoListResponse, encodeToDo, encodeToDoAddRequest, encodeToDoDeleteRequest, encodeToDoGetRequest, encodeToDoListRequest, encodeToDoListResponse, fieldNumbersToDo, fieldNumbersToDoAddRequest, fieldNumbersToDoDeleteRequest, fieldNumbersToDoGetRequest, fieldNumbersToDoListRequest, fieldNumbersToDoListResponse)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 3.2.0
- `protoc` 4.24.4
- the following specification files: `todo.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.


@docs ToDo, ToDoAddRequest, ToDoDeleteRequest, ToDoGetRequest, ToDoListRequest, ToDoListResponse, decodeToDo, decodeToDoAddRequest
@docs decodeToDoDeleteRequest, decodeToDoGetRequest, decodeToDoListRequest, decodeToDoListResponse, defaultToDo, defaultToDoAddRequest
@docs defaultToDoDeleteRequest, defaultToDoGetRequest, defaultToDoListRequest, defaultToDoListResponse, encodeToDo, encodeToDoAddRequest
@docs encodeToDoDeleteRequest, encodeToDoGetRequest, encodeToDoListRequest, encodeToDoListResponse, fieldNumbersToDo
@docs fieldNumbersToDoAddRequest, fieldNumbersToDoDeleteRequest, fieldNumbersToDoGetRequest, fieldNumbersToDoListRequest
@docs fieldNumbersToDoListResponse
-}

import Proto.Api.Todo.Internals_
import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `ToDo`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersToDo : { id : Int, info : Int }
fieldNumbersToDo =
    Proto.Api.Todo.Internals_.fieldNumbersProto__Api__Todo__ToDo


{-| Default for ToDo. Should only be used for 'required' decoders as an initial value.


-}
defaultToDo : ToDo
defaultToDo =
    Proto.Api.Todo.Internals_.defaultProto__Api__Todo__ToDo


{-| Declares how to decode a `ToDo` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeToDo : Protobuf.Decode.Decoder ToDo
decodeToDo =
    Proto.Api.Todo.Internals_.decodeProto__Api__Todo__ToDo


{-| Declares how to encode a `ToDo` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeToDo : ToDo -> Protobuf.Encode.Encoder
encodeToDo =
    Proto.Api.Todo.Internals_.encodeProto__Api__Todo__ToDo


{-| `ToDo` message


-}
type alias ToDo =
    Proto.Api.Todo.Internals_.Proto__Api__Todo__ToDo


{-| The field numbers for the fields of `ToDoDeleteRequest`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersToDoDeleteRequest : { id : Int }
fieldNumbersToDoDeleteRequest =
    Proto.Api.Todo.Internals_.fieldNumbersProto__Api__Todo__ToDoDeleteRequest


{-| Default for ToDoDeleteRequest. Should only be used for 'required' decoders as an initial value.


-}
defaultToDoDeleteRequest : ToDoDeleteRequest
defaultToDoDeleteRequest =
    Proto.Api.Todo.Internals_.defaultProto__Api__Todo__ToDoDeleteRequest


{-| Declares how to decode a `ToDoDeleteRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeToDoDeleteRequest : Protobuf.Decode.Decoder ToDoDeleteRequest
decodeToDoDeleteRequest =
    Proto.Api.Todo.Internals_.decodeProto__Api__Todo__ToDoDeleteRequest


{-| Declares how to encode a `ToDoDeleteRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeToDoDeleteRequest : ToDoDeleteRequest -> Protobuf.Encode.Encoder
encodeToDoDeleteRequest =
    Proto.Api.Todo.Internals_.encodeProto__Api__Todo__ToDoDeleteRequest


{-| `ToDoDeleteRequest` message


-}
type alias ToDoDeleteRequest =
    Proto.Api.Todo.Internals_.Proto__Api__Todo__ToDoDeleteRequest


{-| The field numbers for the fields of `ToDoAddRequest`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersToDoAddRequest : { info : Int }
fieldNumbersToDoAddRequest =
    Proto.Api.Todo.Internals_.fieldNumbersProto__Api__Todo__ToDoAddRequest


{-| Default for ToDoAddRequest. Should only be used for 'required' decoders as an initial value.


-}
defaultToDoAddRequest : ToDoAddRequest
defaultToDoAddRequest =
    Proto.Api.Todo.Internals_.defaultProto__Api__Todo__ToDoAddRequest


{-| Declares how to decode a `ToDoAddRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeToDoAddRequest : Protobuf.Decode.Decoder ToDoAddRequest
decodeToDoAddRequest =
    Proto.Api.Todo.Internals_.decodeProto__Api__Todo__ToDoAddRequest


{-| Declares how to encode a `ToDoAddRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeToDoAddRequest : ToDoAddRequest -> Protobuf.Encode.Encoder
encodeToDoAddRequest =
    Proto.Api.Todo.Internals_.encodeProto__Api__Todo__ToDoAddRequest


{-| `ToDoAddRequest` message


-}
type alias ToDoAddRequest =
    Proto.Api.Todo.Internals_.Proto__Api__Todo__ToDoAddRequest


{-| The field numbers for the fields of `ToDoGetRequest`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersToDoGetRequest : { id : Int }
fieldNumbersToDoGetRequest =
    Proto.Api.Todo.Internals_.fieldNumbersProto__Api__Todo__ToDoGetRequest


{-| Default for ToDoGetRequest. Should only be used for 'required' decoders as an initial value.


-}
defaultToDoGetRequest : ToDoGetRequest
defaultToDoGetRequest =
    Proto.Api.Todo.Internals_.defaultProto__Api__Todo__ToDoGetRequest


{-| Declares how to decode a `ToDoGetRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeToDoGetRequest : Protobuf.Decode.Decoder ToDoGetRequest
decodeToDoGetRequest =
    Proto.Api.Todo.Internals_.decodeProto__Api__Todo__ToDoGetRequest


{-| Declares how to encode a `ToDoGetRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeToDoGetRequest : ToDoGetRequest -> Protobuf.Encode.Encoder
encodeToDoGetRequest =
    Proto.Api.Todo.Internals_.encodeProto__Api__Todo__ToDoGetRequest


{-| `ToDoGetRequest` message


-}
type alias ToDoGetRequest =
    Proto.Api.Todo.Internals_.Proto__Api__Todo__ToDoGetRequest


{-| The field numbers for the fields of `ToDoListResponse`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersToDoListResponse : { todos : Int }
fieldNumbersToDoListResponse =
    Proto.Api.Todo.Internals_.fieldNumbersProto__Api__Todo__ToDoListResponse


{-| Default for ToDoListResponse. Should only be used for 'required' decoders as an initial value.


-}
defaultToDoListResponse : ToDoListResponse
defaultToDoListResponse =
    Proto.Api.Todo.Internals_.defaultProto__Api__Todo__ToDoListResponse


{-| Declares how to decode a `ToDoListResponse` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeToDoListResponse : Protobuf.Decode.Decoder ToDoListResponse
decodeToDoListResponse =
    Proto.Api.Todo.Internals_.decodeProto__Api__Todo__ToDoListResponse


{-| Declares how to encode a `ToDoListResponse` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeToDoListResponse : ToDoListResponse -> Protobuf.Encode.Encoder
encodeToDoListResponse =
    Proto.Api.Todo.Internals_.encodeProto__Api__Todo__ToDoListResponse


{-| `ToDoListResponse` message


-}
type alias ToDoListResponse =
    Proto.Api.Todo.Internals_.Proto__Api__Todo__ToDoListResponse


{-| The field numbers for the fields of `ToDoListRequest`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersToDoListRequest : {}
fieldNumbersToDoListRequest =
    Proto.Api.Todo.Internals_.fieldNumbersProto__Api__Todo__ToDoListRequest


{-| Default for ToDoListRequest. Should only be used for 'required' decoders as an initial value.


-}
defaultToDoListRequest : ToDoListRequest
defaultToDoListRequest =
    Proto.Api.Todo.Internals_.defaultProto__Api__Todo__ToDoListRequest


{-| Declares how to decode a `ToDoListRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeToDoListRequest : Protobuf.Decode.Decoder ToDoListRequest
decodeToDoListRequest =
    Proto.Api.Todo.Internals_.decodeProto__Api__Todo__ToDoListRequest


{-| Declares how to encode a `ToDoListRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeToDoListRequest : ToDoListRequest -> Protobuf.Encode.Encoder
encodeToDoListRequest =
    Proto.Api.Todo.Internals_.encodeProto__Api__Todo__ToDoListRequest


{-| `ToDoListRequest` message


-}
type alias ToDoListRequest =
    Proto.Api.Todo.Internals_.Proto__Api__Todo__ToDoListRequest
