version: "3"

services:
  protoc:
    build:
      context: .
      dockerfile: ./build/protoc/Dockerfile
    working_dir: /usr/src/backend/
    volumes:
      - ../:/usr/src/

  mongo:
    image: mongo
    restart: always
    volumes:
      - /data/db:/data/db
    ports:
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwd
    networks:
      - default

  mongo-admin:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: passwd
      ME_CONFIG_MONGODB_URL: mongodb://root:passwd@mongo:27017
  
  app:
    build:
      context: ..
      dockerfile: ./backend/build/app/dev/Dockerfile
    working_dir: /usr/src/
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/
    networks:
        - default
