{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Api exposing (Task, TaskCreateRequest, TaskCreateResponse, TaskDeleteRequest, TaskDeleteResponse, TaskGetRequest, TaskGetResponse, TaskListRequest, TaskListResponse, TaskUpdateRequest, TaskUpdateResponse, decodeTask, decodeTaskCreateRequest, decodeTaskCreateResponse, decodeTaskDeleteRequest, decodeTaskDeleteResponse, decodeTaskGetRequest, decodeTaskGetResponse, decodeTaskListRequest, decodeTaskListResponse, decodeTaskUpdateRequest, decodeTaskUpdateResponse, defaultTask, defaultTaskCreateRequest, defaultTaskCreateResponse, defaultTaskDeleteRequest, defaultTaskDeleteResponse, defaultTaskGetRequest, defaultTaskGetResponse, defaultTaskListRequest, defaultTaskListResponse, defaultTaskUpdateRequest, defaultTaskUpdateResponse, encodeTask, encodeTaskCreateRequest, encodeTaskCreateResponse, encodeTaskDeleteRequest, encodeTaskDeleteResponse, encodeTaskGetRequest, encodeTaskGetResponse, encodeTaskListRequest, encodeTaskListResponse, encodeTaskUpdateRequest, encodeTaskUpdateResponse, fieldNumbersTask, fieldNumbersTaskCreateRequest, fieldNumbersTaskCreateResponse, fieldNumbersTaskDeleteRequest, fieldNumbersTaskDeleteResponse, fieldNumbersTaskGetRequest, fieldNumbersTaskGetResponse, fieldNumbersTaskListRequest, fieldNumbersTaskListResponse, fieldNumbersTaskUpdateRequest, fieldNumbersTaskUpdateResponse)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 3.2.0
- `protoc` 4.24.4
- the following specification files: `task.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.


@docs Task, TaskCreateRequest, TaskCreateResponse, TaskDeleteRequest, TaskDeleteResponse, TaskGetRequest, TaskGetResponse, TaskListRequest
@docs TaskListResponse, TaskUpdateRequest, TaskUpdateResponse, decodeTask, decodeTaskCreateRequest, decodeTaskCreateResponse
@docs decodeTaskDeleteRequest, decodeTaskDeleteResponse, decodeTaskGetRequest, decodeTaskGetResponse, decodeTaskListRequest
@docs decodeTaskListResponse, decodeTaskUpdateRequest, decodeTaskUpdateResponse, defaultTask, defaultTaskCreateRequest
@docs defaultTaskCreateResponse, defaultTaskDeleteRequest, defaultTaskDeleteResponse, defaultTaskGetRequest, defaultTaskGetResponse
@docs defaultTaskListRequest, defaultTaskListResponse, defaultTaskUpdateRequest, defaultTaskUpdateResponse, encodeTask
@docs encodeTaskCreateRequest, encodeTaskCreateResponse, encodeTaskDeleteRequest, encodeTaskDeleteResponse, encodeTaskGetRequest
@docs encodeTaskGetResponse, encodeTaskListRequest, encodeTaskListResponse, encodeTaskUpdateRequest, encodeTaskUpdateResponse
@docs fieldNumbersTask, fieldNumbersTaskCreateRequest, fieldNumbersTaskCreateResponse, fieldNumbersTaskDeleteRequest
@docs fieldNumbersTaskDeleteResponse, fieldNumbersTaskGetRequest, fieldNumbersTaskGetResponse, fieldNumbersTaskListRequest
@docs fieldNumbersTaskListResponse, fieldNumbersTaskUpdateRequest, fieldNumbersTaskUpdateResponse
-}

import Proto.Api.Internals_
import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `Task`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersTask : { id : Int, info : Int }
fieldNumbersTask =
    Proto.Api.Internals_.fieldNumbersProto__Api__Task


{-| Default for Task. Should only be used for 'required' decoders as an initial value.


-}
defaultTask : Task
defaultTask =
    Proto.Api.Internals_.defaultProto__Api__Task


{-| Declares how to decode a `Task` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeTask : Protobuf.Decode.Decoder Task
decodeTask =
    Proto.Api.Internals_.decodeProto__Api__Task


{-| Declares how to encode a `Task` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeTask : Task -> Protobuf.Encode.Encoder
encodeTask =
    Proto.Api.Internals_.encodeProto__Api__Task


{-| `Task` message


-}
type alias Task =
    Proto.Api.Internals_.Proto__Api__Task


{-| The field numbers for the fields of `TaskDeleteResponse`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersTaskDeleteResponse : { tasks : Int }
fieldNumbersTaskDeleteResponse =
    Proto.Api.Internals_.fieldNumbersProto__Api__TaskDeleteResponse


{-| Default for TaskDeleteResponse. Should only be used for 'required' decoders as an initial value.


-}
defaultTaskDeleteResponse : TaskDeleteResponse
defaultTaskDeleteResponse =
    Proto.Api.Internals_.defaultProto__Api__TaskDeleteResponse


{-| Declares how to decode a `TaskDeleteResponse` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeTaskDeleteResponse : Protobuf.Decode.Decoder TaskDeleteResponse
decodeTaskDeleteResponse =
    Proto.Api.Internals_.decodeProto__Api__TaskDeleteResponse


{-| Declares how to encode a `TaskDeleteResponse` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeTaskDeleteResponse : TaskDeleteResponse -> Protobuf.Encode.Encoder
encodeTaskDeleteResponse =
    Proto.Api.Internals_.encodeProto__Api__TaskDeleteResponse


{-| `TaskDeleteResponse` message


-}
type alias TaskDeleteResponse =
    Proto.Api.Internals_.Proto__Api__TaskDeleteResponse


{-| The field numbers for the fields of `TaskDeleteRequest`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersTaskDeleteRequest : { id : Int }
fieldNumbersTaskDeleteRequest =
    Proto.Api.Internals_.fieldNumbersProto__Api__TaskDeleteRequest


{-| Default for TaskDeleteRequest. Should only be used for 'required' decoders as an initial value.


-}
defaultTaskDeleteRequest : TaskDeleteRequest
defaultTaskDeleteRequest =
    Proto.Api.Internals_.defaultProto__Api__TaskDeleteRequest


{-| Declares how to decode a `TaskDeleteRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeTaskDeleteRequest : Protobuf.Decode.Decoder TaskDeleteRequest
decodeTaskDeleteRequest =
    Proto.Api.Internals_.decodeProto__Api__TaskDeleteRequest


{-| Declares how to encode a `TaskDeleteRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeTaskDeleteRequest : TaskDeleteRequest -> Protobuf.Encode.Encoder
encodeTaskDeleteRequest =
    Proto.Api.Internals_.encodeProto__Api__TaskDeleteRequest


{-| `TaskDeleteRequest` message


-}
type alias TaskDeleteRequest =
    Proto.Api.Internals_.Proto__Api__TaskDeleteRequest


{-| The field numbers for the fields of `TaskUpdateResponse`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersTaskUpdateResponse : { tasks : Int }
fieldNumbersTaskUpdateResponse =
    Proto.Api.Internals_.fieldNumbersProto__Api__TaskUpdateResponse


{-| Default for TaskUpdateResponse. Should only be used for 'required' decoders as an initial value.


-}
defaultTaskUpdateResponse : TaskUpdateResponse
defaultTaskUpdateResponse =
    Proto.Api.Internals_.defaultProto__Api__TaskUpdateResponse


{-| Declares how to decode a `TaskUpdateResponse` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeTaskUpdateResponse : Protobuf.Decode.Decoder TaskUpdateResponse
decodeTaskUpdateResponse =
    Proto.Api.Internals_.decodeProto__Api__TaskUpdateResponse


{-| Declares how to encode a `TaskUpdateResponse` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeTaskUpdateResponse : TaskUpdateResponse -> Protobuf.Encode.Encoder
encodeTaskUpdateResponse =
    Proto.Api.Internals_.encodeProto__Api__TaskUpdateResponse


{-| `TaskUpdateResponse` message


-}
type alias TaskUpdateResponse =
    Proto.Api.Internals_.Proto__Api__TaskUpdateResponse


{-| The field numbers for the fields of `TaskUpdateRequest`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersTaskUpdateRequest : { task : Int }
fieldNumbersTaskUpdateRequest =
    Proto.Api.Internals_.fieldNumbersProto__Api__TaskUpdateRequest


{-| Default for TaskUpdateRequest. Should only be used for 'required' decoders as an initial value.


-}
defaultTaskUpdateRequest : TaskUpdateRequest
defaultTaskUpdateRequest =
    Proto.Api.Internals_.defaultProto__Api__TaskUpdateRequest


{-| Declares how to decode a `TaskUpdateRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeTaskUpdateRequest : Protobuf.Decode.Decoder TaskUpdateRequest
decodeTaskUpdateRequest =
    Proto.Api.Internals_.decodeProto__Api__TaskUpdateRequest


{-| Declares how to encode a `TaskUpdateRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeTaskUpdateRequest : TaskUpdateRequest -> Protobuf.Encode.Encoder
encodeTaskUpdateRequest =
    Proto.Api.Internals_.encodeProto__Api__TaskUpdateRequest


{-| `TaskUpdateRequest` message


-}
type alias TaskUpdateRequest =
    Proto.Api.Internals_.Proto__Api__TaskUpdateRequest


{-| The field numbers for the fields of `TaskCreateResponse`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersTaskCreateResponse : { tasks : Int }
fieldNumbersTaskCreateResponse =
    Proto.Api.Internals_.fieldNumbersProto__Api__TaskCreateResponse


{-| Default for TaskCreateResponse. Should only be used for 'required' decoders as an initial value.


-}
defaultTaskCreateResponse : TaskCreateResponse
defaultTaskCreateResponse =
    Proto.Api.Internals_.defaultProto__Api__TaskCreateResponse


{-| Declares how to decode a `TaskCreateResponse` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeTaskCreateResponse : Protobuf.Decode.Decoder TaskCreateResponse
decodeTaskCreateResponse =
    Proto.Api.Internals_.decodeProto__Api__TaskCreateResponse


{-| Declares how to encode a `TaskCreateResponse` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeTaskCreateResponse : TaskCreateResponse -> Protobuf.Encode.Encoder
encodeTaskCreateResponse =
    Proto.Api.Internals_.encodeProto__Api__TaskCreateResponse


{-| `TaskCreateResponse` message


-}
type alias TaskCreateResponse =
    Proto.Api.Internals_.Proto__Api__TaskCreateResponse


{-| The field numbers for the fields of `TaskCreateRequest`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersTaskCreateRequest : { info : Int }
fieldNumbersTaskCreateRequest =
    Proto.Api.Internals_.fieldNumbersProto__Api__TaskCreateRequest


{-| Default for TaskCreateRequest. Should only be used for 'required' decoders as an initial value.


-}
defaultTaskCreateRequest : TaskCreateRequest
defaultTaskCreateRequest =
    Proto.Api.Internals_.defaultProto__Api__TaskCreateRequest


{-| Declares how to decode a `TaskCreateRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeTaskCreateRequest : Protobuf.Decode.Decoder TaskCreateRequest
decodeTaskCreateRequest =
    Proto.Api.Internals_.decodeProto__Api__TaskCreateRequest


{-| Declares how to encode a `TaskCreateRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeTaskCreateRequest : TaskCreateRequest -> Protobuf.Encode.Encoder
encodeTaskCreateRequest =
    Proto.Api.Internals_.encodeProto__Api__TaskCreateRequest


{-| `TaskCreateRequest` message


-}
type alias TaskCreateRequest =
    Proto.Api.Internals_.Proto__Api__TaskCreateRequest


{-| The field numbers for the fields of `TaskGetResponse`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersTaskGetResponse : { task : Int }
fieldNumbersTaskGetResponse =
    Proto.Api.Internals_.fieldNumbersProto__Api__TaskGetResponse


{-| Default for TaskGetResponse. Should only be used for 'required' decoders as an initial value.


-}
defaultTaskGetResponse : TaskGetResponse
defaultTaskGetResponse =
    Proto.Api.Internals_.defaultProto__Api__TaskGetResponse


{-| Declares how to decode a `TaskGetResponse` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeTaskGetResponse : Protobuf.Decode.Decoder TaskGetResponse
decodeTaskGetResponse =
    Proto.Api.Internals_.decodeProto__Api__TaskGetResponse


{-| Declares how to encode a `TaskGetResponse` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeTaskGetResponse : TaskGetResponse -> Protobuf.Encode.Encoder
encodeTaskGetResponse =
    Proto.Api.Internals_.encodeProto__Api__TaskGetResponse


{-| `TaskGetResponse` message


-}
type alias TaskGetResponse =
    Proto.Api.Internals_.Proto__Api__TaskGetResponse


{-| The field numbers for the fields of `TaskGetRequest`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersTaskGetRequest : { id : Int }
fieldNumbersTaskGetRequest =
    Proto.Api.Internals_.fieldNumbersProto__Api__TaskGetRequest


{-| Default for TaskGetRequest. Should only be used for 'required' decoders as an initial value.


-}
defaultTaskGetRequest : TaskGetRequest
defaultTaskGetRequest =
    Proto.Api.Internals_.defaultProto__Api__TaskGetRequest


{-| Declares how to decode a `TaskGetRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeTaskGetRequest : Protobuf.Decode.Decoder TaskGetRequest
decodeTaskGetRequest =
    Proto.Api.Internals_.decodeProto__Api__TaskGetRequest


{-| Declares how to encode a `TaskGetRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeTaskGetRequest : TaskGetRequest -> Protobuf.Encode.Encoder
encodeTaskGetRequest =
    Proto.Api.Internals_.encodeProto__Api__TaskGetRequest


{-| `TaskGetRequest` message


-}
type alias TaskGetRequest =
    Proto.Api.Internals_.Proto__Api__TaskGetRequest


{-| The field numbers for the fields of `TaskListResponse`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersTaskListResponse : { tasks : Int }
fieldNumbersTaskListResponse =
    Proto.Api.Internals_.fieldNumbersProto__Api__TaskListResponse


{-| Default for TaskListResponse. Should only be used for 'required' decoders as an initial value.


-}
defaultTaskListResponse : TaskListResponse
defaultTaskListResponse =
    Proto.Api.Internals_.defaultProto__Api__TaskListResponse


{-| Declares how to decode a `TaskListResponse` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeTaskListResponse : Protobuf.Decode.Decoder TaskListResponse
decodeTaskListResponse =
    Proto.Api.Internals_.decodeProto__Api__TaskListResponse


{-| Declares how to encode a `TaskListResponse` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeTaskListResponse : TaskListResponse -> Protobuf.Encode.Encoder
encodeTaskListResponse =
    Proto.Api.Internals_.encodeProto__Api__TaskListResponse


{-| `TaskListResponse` message


-}
type alias TaskListResponse =
    Proto.Api.Internals_.Proto__Api__TaskListResponse


{-| The field numbers for the fields of `TaskListRequest`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersTaskListRequest : {}
fieldNumbersTaskListRequest =
    Proto.Api.Internals_.fieldNumbersProto__Api__TaskListRequest


{-| Default for TaskListRequest. Should only be used for 'required' decoders as an initial value.


-}
defaultTaskListRequest : TaskListRequest
defaultTaskListRequest =
    Proto.Api.Internals_.defaultProto__Api__TaskListRequest


{-| Declares how to decode a `TaskListRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeTaskListRequest : Protobuf.Decode.Decoder TaskListRequest
decodeTaskListRequest =
    Proto.Api.Internals_.decodeProto__Api__TaskListRequest


{-| Declares how to encode a `TaskListRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeTaskListRequest : TaskListRequest -> Protobuf.Encode.Encoder
encodeTaskListRequest =
    Proto.Api.Internals_.encodeProto__Api__TaskListRequest


{-| `TaskListRequest` message


-}
type alias TaskListRequest =
    Proto.Api.Internals_.Proto__Api__TaskListRequest
