{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Api.Todo.Internals_ exposing (..)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 3.2.0
- `protoc` 4.24.4
- the following specification files: `todo.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.


-}

import Bytes
import Maybe
import Proto.Google.Protobuf.Internals_
import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `Proto__Api__Todo__ToDo__Info`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersProto__Api__Todo__ToDo__Info :
    { title : Int, description : Int, limit : Int, priority : Int, status : Int, labels : Int }
fieldNumbersProto__Api__Todo__ToDo__Info =
    { title = 1, description = 2, limit = 3, priority = 4, status = 5, labels = 6 }


{-| Default for Proto__Api__Todo__ToDo__Info. Should only be used for 'required' decoders as an initial value.


-}
defaultProto__Api__Todo__ToDo__Info : Proto__Api__Todo__ToDo__Info
defaultProto__Api__Todo__ToDo__Info =
    { title = ""
    , description = ""
    , limit = Nothing
    , priority = defaultProto__Api__Todo__ToDo__Info__Priority
    , status = defaultProto__Api__Todo__ToDo__Info__Status
    , labels = []
    }


{-| Declares how to decode a `Proto__Api__Todo__ToDo__Info` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeProto__Api__Todo__ToDo__Info : Protobuf.Decode.Decoder Proto__Api__Todo__ToDo__Info
decodeProto__Api__Todo__ToDo__Info =
    Protobuf.Decode.message
        defaultProto__Api__Todo__ToDo__Info
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | title = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.string (\a r -> { r | description = a })
        , Protobuf.Decode.optional
            3
            (Protobuf.Decode.map Just Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__Timestamp)
            (\a r -> { r | limit = a })
        , Protobuf.Decode.optional 4 decodeProto__Api__Todo__ToDo__Info__Priority (\a r -> { r | priority = a })
        , Protobuf.Decode.optional 5 decodeProto__Api__Todo__ToDo__Info__Status (\a r -> { r | status = a })
        , Protobuf.Decode.repeated 6 Protobuf.Decode.string .labels (\a r -> { r | labels = a })
        ]


{-| Declares how to encode a `Proto__Api__Todo__ToDo__Info` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeProto__Api__Todo__ToDo__Info : Proto__Api__Todo__ToDo__Info -> Protobuf.Encode.Encoder
encodeProto__Api__Todo__ToDo__Info value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.title )
        , ( 2, Protobuf.Encode.string value.description )
        , ( 3
          , (Maybe.map Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__Timestamp
                >> Maybe.withDefault Protobuf.Encode.none
            )
                value.limit
          )
        , ( 4, encodeProto__Api__Todo__ToDo__Info__Priority value.priority )
        , ( 5, encodeProto__Api__Todo__ToDo__Info__Status value.status )
        , ( 6, Protobuf.Encode.list Protobuf.Encode.string value.labels )
        ]


{-| `Proto__Api__Todo__ToDo__Info` message


-}
type alias Proto__Api__Todo__ToDo__Info =
    { title : String
    , description : String
    , limit : Maybe Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__Timestamp
    , priority : Proto__Api__Todo__ToDo__Info__Priority
    , status : Proto__Api__Todo__ToDo__Info__Status
    , labels : List String
    }


{-| The field numbers for the fields of `Proto__Api__Todo__ToDo`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersProto__Api__Todo__ToDo : { id : Int, info : Int }
fieldNumbersProto__Api__Todo__ToDo =
    { id = 1, info = 2 }


{-| Default for Proto__Api__Todo__ToDo. Should only be used for 'required' decoders as an initial value.


-}
defaultProto__Api__Todo__ToDo : Proto__Api__Todo__ToDo
defaultProto__Api__Todo__ToDo =
    { id = Protobuf.Encode.encode <| Protobuf.Encode.string "", info = Nothing }


{-| Declares how to decode a `Proto__Api__Todo__ToDo` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeProto__Api__Todo__ToDo : Protobuf.Decode.Decoder Proto__Api__Todo__ToDo
decodeProto__Api__Todo__ToDo =
    Protobuf.Decode.message
        defaultProto__Api__Todo__ToDo
        [ Protobuf.Decode.optional 1 Protobuf.Decode.bytes (\a r -> { r | id = a })
        , Protobuf.Decode.optional
            2
            (Protobuf.Decode.map Just decodeProto__Api__Todo__ToDo__Info)
            (\a r -> { r | info = a })
        ]


{-| Declares how to encode a `Proto__Api__Todo__ToDo` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeProto__Api__Todo__ToDo : Proto__Api__Todo__ToDo -> Protobuf.Encode.Encoder
encodeProto__Api__Todo__ToDo value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.bytes value.id )
        , ( 2, (Maybe.map encodeProto__Api__Todo__ToDo__Info >> Maybe.withDefault Protobuf.Encode.none) value.info )
        ]


{-| `Proto__Api__Todo__ToDo` message


-}
type alias Proto__Api__Todo__ToDo =
    { id : Bytes.Bytes, info : Maybe Proto__Api__Todo__ToDo__Info }


{-| The field numbers for the fields of `Proto__Api__Todo__ToDoDeleteRequest`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersProto__Api__Todo__ToDoDeleteRequest : { id : Int }
fieldNumbersProto__Api__Todo__ToDoDeleteRequest =
    { id = 1 }


{-| Default for Proto__Api__Todo__ToDoDeleteRequest. Should only be used for 'required' decoders as an initial value.


-}
defaultProto__Api__Todo__ToDoDeleteRequest : Proto__Api__Todo__ToDoDeleteRequest
defaultProto__Api__Todo__ToDoDeleteRequest =
    { id = 0 }


{-| Declares how to decode a `Proto__Api__Todo__ToDoDeleteRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeProto__Api__Todo__ToDoDeleteRequest : Protobuf.Decode.Decoder Proto__Api__Todo__ToDoDeleteRequest
decodeProto__Api__Todo__ToDoDeleteRequest =
    Protobuf.Decode.message
        defaultProto__Api__Todo__ToDoDeleteRequest
        [ Protobuf.Decode.optional 1 Protobuf.Decode.int32 (\a r -> { r | id = a }) ]


{-| Declares how to encode a `Proto__Api__Todo__ToDoDeleteRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeProto__Api__Todo__ToDoDeleteRequest : Proto__Api__Todo__ToDoDeleteRequest -> Protobuf.Encode.Encoder
encodeProto__Api__Todo__ToDoDeleteRequest value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.int32 value.id ) ]


{-| `Proto__Api__Todo__ToDoDeleteRequest` message


-}
type alias Proto__Api__Todo__ToDoDeleteRequest =
    { id : Int }


{-| The field numbers for the fields of `Proto__Api__Todo__ToDoAddRequest`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersProto__Api__Todo__ToDoAddRequest : { info : Int }
fieldNumbersProto__Api__Todo__ToDoAddRequest =
    { info = 1 }


{-| Default for Proto__Api__Todo__ToDoAddRequest. Should only be used for 'required' decoders as an initial value.


-}
defaultProto__Api__Todo__ToDoAddRequest : Proto__Api__Todo__ToDoAddRequest
defaultProto__Api__Todo__ToDoAddRequest =
    { info = Nothing }


{-| Declares how to decode a `Proto__Api__Todo__ToDoAddRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeProto__Api__Todo__ToDoAddRequest : Protobuf.Decode.Decoder Proto__Api__Todo__ToDoAddRequest
decodeProto__Api__Todo__ToDoAddRequest =
    Protobuf.Decode.message
        defaultProto__Api__Todo__ToDoAddRequest
        [ Protobuf.Decode.optional
            1
            (Protobuf.Decode.map Just decodeProto__Api__Todo__ToDo__Info)
            (\a r -> { r | info = a })
        ]


{-| Declares how to encode a `Proto__Api__Todo__ToDoAddRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeProto__Api__Todo__ToDoAddRequest : Proto__Api__Todo__ToDoAddRequest -> Protobuf.Encode.Encoder
encodeProto__Api__Todo__ToDoAddRequest value =
    Protobuf.Encode.message
        [ ( 1, (Maybe.map encodeProto__Api__Todo__ToDo__Info >> Maybe.withDefault Protobuf.Encode.none) value.info ) ]


{-| `Proto__Api__Todo__ToDoAddRequest` message


-}
type alias Proto__Api__Todo__ToDoAddRequest =
    { info : Maybe Proto__Api__Todo__ToDo__Info }


{-| The field numbers for the fields of `Proto__Api__Todo__ToDoGetRequest`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersProto__Api__Todo__ToDoGetRequest : { id : Int }
fieldNumbersProto__Api__Todo__ToDoGetRequest =
    { id = 1 }


{-| Default for Proto__Api__Todo__ToDoGetRequest. Should only be used for 'required' decoders as an initial value.


-}
defaultProto__Api__Todo__ToDoGetRequest : Proto__Api__Todo__ToDoGetRequest
defaultProto__Api__Todo__ToDoGetRequest =
    { id = 0 }


{-| Declares how to decode a `Proto__Api__Todo__ToDoGetRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeProto__Api__Todo__ToDoGetRequest : Protobuf.Decode.Decoder Proto__Api__Todo__ToDoGetRequest
decodeProto__Api__Todo__ToDoGetRequest =
    Protobuf.Decode.message
        defaultProto__Api__Todo__ToDoGetRequest
        [ Protobuf.Decode.optional 1 Protobuf.Decode.int32 (\a r -> { r | id = a }) ]


{-| Declares how to encode a `Proto__Api__Todo__ToDoGetRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeProto__Api__Todo__ToDoGetRequest : Proto__Api__Todo__ToDoGetRequest -> Protobuf.Encode.Encoder
encodeProto__Api__Todo__ToDoGetRequest value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.int32 value.id ) ]


{-| `Proto__Api__Todo__ToDoGetRequest` message


-}
type alias Proto__Api__Todo__ToDoGetRequest =
    { id : Int }


{-| The field numbers for the fields of `Proto__Api__Todo__ToDoListResponse`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersProto__Api__Todo__ToDoListResponse : { todos : Int }
fieldNumbersProto__Api__Todo__ToDoListResponse =
    { todos = 1 }


{-| Default for Proto__Api__Todo__ToDoListResponse. Should only be used for 'required' decoders as an initial value.


-}
defaultProto__Api__Todo__ToDoListResponse : Proto__Api__Todo__ToDoListResponse
defaultProto__Api__Todo__ToDoListResponse =
    { todos = [] }


{-| Declares how to decode a `Proto__Api__Todo__ToDoListResponse` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeProto__Api__Todo__ToDoListResponse : Protobuf.Decode.Decoder Proto__Api__Todo__ToDoListResponse
decodeProto__Api__Todo__ToDoListResponse =
    Protobuf.Decode.message
        defaultProto__Api__Todo__ToDoListResponse
        [ Protobuf.Decode.repeated 1 decodeProto__Api__Todo__ToDo .todos (\a r -> { r | todos = a }) ]


{-| Declares how to encode a `Proto__Api__Todo__ToDoListResponse` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeProto__Api__Todo__ToDoListResponse : Proto__Api__Todo__ToDoListResponse -> Protobuf.Encode.Encoder
encodeProto__Api__Todo__ToDoListResponse value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.list encodeProto__Api__Todo__ToDo value.todos ) ]


{-| `Proto__Api__Todo__ToDoListResponse` message


-}
type alias Proto__Api__Todo__ToDoListResponse =
    { todos : List Proto__Api__Todo__ToDo }


{-| The field numbers for the fields of `Proto__Api__Todo__ToDoListRequest`. This is mostly useful for internals, like documentation generation.


-}
fieldNumbersProto__Api__Todo__ToDoListRequest : {}
fieldNumbersProto__Api__Todo__ToDoListRequest =
    {}


{-| Default for Proto__Api__Todo__ToDoListRequest. Should only be used for 'required' decoders as an initial value.


-}
defaultProto__Api__Todo__ToDoListRequest : Proto__Api__Todo__ToDoListRequest
defaultProto__Api__Todo__ToDoListRequest =
    {}


{-| Declares how to decode a `Proto__Api__Todo__ToDoListRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeProto__Api__Todo__ToDoListRequest : Protobuf.Decode.Decoder Proto__Api__Todo__ToDoListRequest
decodeProto__Api__Todo__ToDoListRequest =
    Protobuf.Decode.message defaultProto__Api__Todo__ToDoListRequest []


{-| Declares how to encode a `Proto__Api__Todo__ToDoListRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeProto__Api__Todo__ToDoListRequest : Proto__Api__Todo__ToDoListRequest -> Protobuf.Encode.Encoder
encodeProto__Api__Todo__ToDoListRequest _ =
    Protobuf.Encode.message []


{-| `Proto__Api__Todo__ToDoListRequest` message


-}
type alias Proto__Api__Todo__ToDoListRequest =
    {}


{-| Default for Proto__Api__Todo__ToDo__Info__Status. Should only be used for 'required' decoders as an initial value.


-}
defaultProto__Api__Todo__ToDo__Info__Status : Proto__Api__Todo__ToDo__Info__Status
defaultProto__Api__Todo__ToDo__Info__Status =
    Proto__Api__Todo__ToDo__Info__STATUSUNSPECIFIED


{-| Declares how to encode a `Proto__Api__Todo__ToDo__Info__Status` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeProto__Api__Todo__ToDo__Info__Status : Proto__Api__Todo__ToDo__Info__Status -> Protobuf.Encode.Encoder
encodeProto__Api__Todo__ToDo__Info__Status value =
    Protobuf.Encode.int32 <|
        case value of
            Proto__Api__Todo__ToDo__Info__STATUSUNSPECIFIED ->
                0

            Proto__Api__Todo__ToDo__Info__STATUSNOTYET ->
                1

            Proto__Api__Todo__ToDo__Info__STATUSDOING ->
                2

            Proto__Api__Todo__ToDo__Info__STATUSDONE ->
                3

            Proto__Api__Todo__ToDo__Info__StatusUnrecognized_ i ->
                i


{-| Declares how to decode a `Proto__Api__Todo__ToDo__Info__Status` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeProto__Api__Todo__ToDo__Info__Status : Protobuf.Decode.Decoder Proto__Api__Todo__ToDo__Info__Status
decodeProto__Api__Todo__ToDo__Info__Status =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        Proto__Api__Todo__ToDo__Info__STATUSUNSPECIFIED

                    1 ->
                        Proto__Api__Todo__ToDo__Info__STATUSNOTYET

                    2 ->
                        Proto__Api__Todo__ToDo__Info__STATUSDOING

                    3 ->
                        Proto__Api__Todo__ToDo__Info__STATUSDONE

                    _ ->
                        Proto__Api__Todo__ToDo__Info__StatusUnrecognized_ i
            )


{-| `Proto__Api__Todo__ToDo__Info__Status` enumeration


-}
type Proto__Api__Todo__ToDo__Info__Status
    = Proto__Api__Todo__ToDo__Info__STATUSUNSPECIFIED
    | Proto__Api__Todo__ToDo__Info__STATUSNOTYET
    | Proto__Api__Todo__ToDo__Info__STATUSDOING
    | Proto__Api__Todo__ToDo__Info__STATUSDONE
    | Proto__Api__Todo__ToDo__Info__StatusUnrecognized_ Int


{-| Default for Proto__Api__Todo__ToDo__Info__Priority. Should only be used for 'required' decoders as an initial value.


-}
defaultProto__Api__Todo__ToDo__Info__Priority : Proto__Api__Todo__ToDo__Info__Priority
defaultProto__Api__Todo__ToDo__Info__Priority =
    Proto__Api__Todo__ToDo__Info__PRIORITYUNSPECIFIED


{-| Declares how to encode a `Proto__Api__Todo__ToDo__Info__Priority` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeProto__Api__Todo__ToDo__Info__Priority : Proto__Api__Todo__ToDo__Info__Priority -> Protobuf.Encode.Encoder
encodeProto__Api__Todo__ToDo__Info__Priority value =
    Protobuf.Encode.int32 <|
        case value of
            Proto__Api__Todo__ToDo__Info__PRIORITYUNSPECIFIED ->
                0

            Proto__Api__Todo__ToDo__Info__PRIORITYLOW ->
                1

            Proto__Api__Todo__ToDo__Info__PRIORITYNORMALMIDDLE ->
                2

            Proto__Api__Todo__ToDo__Info__PRIORITYHIGH ->
                3

            Proto__Api__Todo__ToDo__Info__PriorityUnrecognized_ i ->
                i


{-| Declares how to decode a `Proto__Api__Todo__ToDo__Info__Priority` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeProto__Api__Todo__ToDo__Info__Priority : Protobuf.Decode.Decoder Proto__Api__Todo__ToDo__Info__Priority
decodeProto__Api__Todo__ToDo__Info__Priority =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        Proto__Api__Todo__ToDo__Info__PRIORITYUNSPECIFIED

                    1 ->
                        Proto__Api__Todo__ToDo__Info__PRIORITYLOW

                    2 ->
                        Proto__Api__Todo__ToDo__Info__PRIORITYNORMALMIDDLE

                    3 ->
                        Proto__Api__Todo__ToDo__Info__PRIORITYHIGH

                    _ ->
                        Proto__Api__Todo__ToDo__Info__PriorityUnrecognized_ i
            )


{-| `Proto__Api__Todo__ToDo__Info__Priority` enumeration


-}
type Proto__Api__Todo__ToDo__Info__Priority
    = Proto__Api__Todo__ToDo__Info__PRIORITYUNSPECIFIED
    | Proto__Api__Todo__ToDo__Info__PRIORITYLOW
    | Proto__Api__Todo__ToDo__Info__PRIORITYNORMALMIDDLE
    | Proto__Api__Todo__ToDo__Info__PRIORITYHIGH
    | Proto__Api__Todo__ToDo__Info__PriorityUnrecognized_ Int
