{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Api.Todo.ToDoService exposing (add, delete, get, list, update)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 3.2.0
- `protoc` 4.24.4
- the following specification files: `todo.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.


@docs add, delete, get, list, update
-}

import Grpc.Internal
import Proto.Api.Todo


{-| A template for a gRPC call to the method 'Delete' sending a `ToDoDeleteRequest` to get back a `ToDoListResponse`.


-}
delete : Grpc.Internal.Rpc Proto.Api.Todo.ToDoDeleteRequest Proto.Api.Todo.ToDoListResponse
delete =
    Grpc.Internal.Rpc
        { service = "ToDoService"
        , package = "api.todo"
        , rpcName = "Delete"
        , encoder = Proto.Api.Todo.encodeToDoDeleteRequest
        , decoder = Proto.Api.Todo.decodeToDoListResponse
        }


{-| A template for a gRPC call to the method 'Update' sending a `ToDo` to get back a `ToDoListResponse`.


-}
update : Grpc.Internal.Rpc Proto.Api.Todo.ToDo Proto.Api.Todo.ToDoListResponse
update =
    Grpc.Internal.Rpc
        { service = "ToDoService"
        , package = "api.todo"
        , rpcName = "Update"
        , encoder = Proto.Api.Todo.encodeToDo
        , decoder = Proto.Api.Todo.decodeToDoListResponse
        }


{-| A template for a gRPC call to the method 'Add' sending a `ToDoAddRequest` to get back a `ToDoListResponse`.


-}
add : Grpc.Internal.Rpc Proto.Api.Todo.ToDoAddRequest Proto.Api.Todo.ToDoListResponse
add =
    Grpc.Internal.Rpc
        { service = "ToDoService"
        , package = "api.todo"
        , rpcName = "Add"
        , encoder = Proto.Api.Todo.encodeToDoAddRequest
        , decoder = Proto.Api.Todo.decodeToDoListResponse
        }


{-| A template for a gRPC call to the method 'Get' sending a `ToDoGetRequest` to get back a `ToDo`.


-}
get : Grpc.Internal.Rpc Proto.Api.Todo.ToDoGetRequest Proto.Api.Todo.ToDo
get =
    Grpc.Internal.Rpc
        { service = "ToDoService"
        , package = "api.todo"
        , rpcName = "Get"
        , encoder = Proto.Api.Todo.encodeToDoGetRequest
        , decoder = Proto.Api.Todo.decodeToDo
        }


{-| A template for a gRPC call to the method 'List' sending a `ToDoListRequest` to get back a `ToDoListResponse`.


-}
list : Grpc.Internal.Rpc Proto.Api.Todo.ToDoListRequest Proto.Api.Todo.ToDoListResponse
list =
    Grpc.Internal.Rpc
        { service = "ToDoService"
        , package = "api.todo"
        , rpcName = "List"
        , encoder = Proto.Api.Todo.encodeToDoListRequest
        , decoder = Proto.Api.Todo.decodeToDoListResponse
        }
