#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Nx affected test
target_branch="remotes/$(git rev-parse --abbrev-ref --symbolic-full-name @{u})"
npm run test:affected -- --base=$(git rev-parse --short ${target_branch})
