{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Api.Task.TaskService exposing (add, delete, get, list, update)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 3.2.0
- `protoc` 4.24.4
- the following specification files: `task.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.


@docs add, delete, get, list, update
-}

import Grpc.Internal
import Proto.Api.Task


{-| A template for a gRPC call to the method 'Delete' sending a `TaskDeleteRequest` to get back a `TaskListResponse`.


-}
delete : Grpc.Internal.Rpc Proto.Api.Task.TaskDeleteRequest Proto.Api.Task.TaskListResponse
delete =
    Grpc.Internal.Rpc
        { service = "TaskService"
        , package = "api.task"
        , rpcName = "Delete"
        , encoder = Proto.Api.Task.encodeTaskDeleteRequest
        , decoder = Proto.Api.Task.decodeTaskListResponse
        }


{-| A template for a gRPC call to the method 'Update' sending a `Task` to get back a `TaskListResponse`.


-}
update : Grpc.Internal.Rpc Proto.Api.Task.Task Proto.Api.Task.TaskListResponse
update =
    Grpc.Internal.Rpc
        { service = "TaskService"
        , package = "api.task"
        , rpcName = "Update"
        , encoder = Proto.Api.Task.encodeTask
        , decoder = Proto.Api.Task.decodeTaskListResponse
        }


{-| A template for a gRPC call to the method 'Add' sending a `TaskAddRequest` to get back a `TaskListResponse`.


-}
add : Grpc.Internal.Rpc Proto.Api.Task.TaskAddRequest Proto.Api.Task.TaskListResponse
add =
    Grpc.Internal.Rpc
        { service = "TaskService"
        , package = "api.task"
        , rpcName = "Add"
        , encoder = Proto.Api.Task.encodeTaskAddRequest
        , decoder = Proto.Api.Task.decodeTaskListResponse
        }


{-| A template for a gRPC call to the method 'Get' sending a `TaskGetRequest` to get back a `Task`.


-}
get : Grpc.Internal.Rpc Proto.Api.Task.TaskGetRequest Proto.Api.Task.Task
get =
    Grpc.Internal.Rpc
        { service = "TaskService"
        , package = "api.task"
        , rpcName = "Get"
        , encoder = Proto.Api.Task.encodeTaskGetRequest
        , decoder = Proto.Api.Task.decodeTask
        }


{-| A template for a gRPC call to the method 'List' sending a `TaskListRequest` to get back a `TaskListResponse`.


-}
list : Grpc.Internal.Rpc Proto.Api.Task.TaskListRequest Proto.Api.Task.TaskListResponse
list =
    Grpc.Internal.Rpc
        { service = "TaskService"
        , package = "api.task"
        , rpcName = "List"
        , encoder = Proto.Api.Task.encodeTaskListRequest
        , decoder = Proto.Api.Task.decodeTaskListResponse
        }
